### ISSUE TITLE
Large Sector Sizes

### ISSUE THREAD

**Issue by leofidus** [ColinFinck/ntfs#14]
As @msuhanov noted in #12, Arsenal Image Mounter can emulate 4kn/512e devices. This indeed allows you to create valid  If you mount an image as writable and format it with Windows, you get an NTFS file system with 4096 sector size.

Here's an example image, which when mounted in Arsenal Image Mounter with 4k sector size and as "removable device" (because I didn't include a partition table) is recognized as a normal NTFS filesystem: [empty-4kSectors-8GB.img.gz](https://github.com/ColinFinck/ntfs/files/8244595/empty-4kSectors-8GB.img.gz)
 
Using the same method I was also able to create images with sector sizes of 1024 and 2048 bytes. 8192 bytes and larger fails: Windows can create the partition, but can't format it. This matches with my comment in #12 about the sector size being limited by the page size (so what about Windows on an Alpha or Itanium system with 8k pages? Probably not that relevant though).

**Comment by ColinFinck** [comment]
Should work now up to sector sizes of 4K.
Thanks for the Arsenal Image Mounter tip @msuhanov and the test image @leofidus!
