### ISSUE TITLE
UEFI support

### ISSUE THREAD

**Issue by drsuser** [ColinFinck/ntfs#15]
Hi, any idea what it would take to compile this driver for EFI? Has this been considered yet?

**Comment by ColinFinck** [comment]
My ntfs crate has been written with a `no_std` + `alloc` environment (like UEFI) in mind right from the start.
For example, you can use the [uefi-rs](https://github.com/rust-osdev/uefi-rs) crate, enable its `alloc` feature, and you should be all set for using my crate.

I'm also still improving the `no_std` support of my crate whenever I notice shortcomings.
An example is the [recent move from `chrono` to the `no_std`-compatible `time` crate](https://github.com/ColinFinck/ntfs/commit/d54266330757ad2da3da38cd17ff1445a9cee4ae) for the optional timestamp parsing support.

**Comment by ColinFinck** [comment]
Closing this issue as there are no actionable tasks.
If you have a specific issue with using my crate in a UEFI environment, please open a new issue.
