### ISSUE TITLE
NtfsFile::data string comparison is not case insensitive

### ISSUE THREAD

**Issue by vthib** [ColinFinck/ntfs#17]
Trying to find a given data stream in a file from its name ( https://docs.rs/ntfs/latest/ntfs/struct.NtfsFile.html#method.data ) requires matching the exact case of the data stream.

From my tests, ADS names are also treated in a case insensitive manner by windows. Invoking `notepad file:stream` or `notepad FILE:STREAM` will open the same data stream.

IMHO this isn't really a bug, given that handling case insensitivity requires building the upcase table and knowing which functions handle it properly. But it is a "surprising" behavior and I got caught by it :).

I think adding a new data method that handles case insensitivity (this is pretty trivial to do, just need to pass the Ntfs object and call upcase_cmp) and improving the documentation on the data method to specify this behavior would be nice, and would allow implementing the full usecase of retrieving the data from a path + stream name). What do you think?

**Comment by ColinFinck** [comment]
Thanks for bringing this up! Indeed, I didn't think about case-insensitivity for the names of NTFS Alternate Data Streams. But you are right, Windows is case-insensitive here and uses the same $UpCase table as for NTFS filenames.

As `NtfsFile::data` is a convenience method, I'm leaning towards changing it to perform a case-insensitive comparison - without adding another method.
It would then require the user to have called `Ntfs::read_upcase_table` prior to using `NtfsFile::data`, or `NtfsFile::data` panics, but this should be acceptable. An exception could be made if we're looking for the default $DATA attribute and `data_stream_name` is empty.

This would be a breaking change, but the crate is still young enough for such changes.

How does that sound?

**Comment by ColinFinck** [comment]
I've committed my proposed change in b0058b9b9a19bd6727a8be7ef603d1e4421255ed
Please let me know if that works for you.

**Comment by vthib** [comment]
Perfect, thanks a lot!
