### ISSUE TITLE
Crash in `Record::fixup`, `array_position_end` out of bounds of `self.data`

### ISSUE THREAD

**Issue by Arthur-PI** [ColinFinck/ntfs#24]
Hello again (😢), I have a new crash with the latest fixes, so here it is.  
During `Record` fixup I think an invalid ntfs data that is lying on sizes is leading to this and here is the file to reproduce: [test.zip](https://github.com/ColinFinck/ntfs/files/10490552/test.zip)  
So Here is what I observed:  
The lines that crashes are those ones
https://github.com/ColinFinck/ntfs/blob/e3671c58f1e27f1fa24fa73cf07d120d774bfc46/src/record.rs#L59-L62
Here `self.data.len()` is `1024` and `array_position_end` is `1025` so the out of bounds panics.
There is an if statement that validate the data length but I don't think that this is the problem.
https://github.com/ColinFinck/ntfs/blob/e3671c58f1e27f1fa24fa73cf07d120d774bfc46/src/record.rs#L51-L57

My guess is that `array_end` is wrong in the loop condition before that
https://github.com/ColinFinck/ntfs/blob/e3671c58f1e27f1fa24fa73cf07d120d774bfc46/src/record.rs#L47
Here `array_end` is `120827` and `array_position` is `1025` and is incrementing of 2 each loop iteration so  its gonna take time before this exits. And `array_end` is build from this https://github.com/ColinFinck/ntfs/blob/e3671c58f1e27f1fa24fa73cf07d120d774bfc46/src/record.rs#L41-L42
`self.update_sequence_size()` is `1019` which is quite relevant in this situation but the offset it going to the sky because `update_sequence_offset()` is `119808`.  
So here were my thoughts, I don't have the necesserry knowledge to fix this properly so I leave the details to you 😄

**Comment by ColinFinck** [comment]
Thanks again for this bug report, which came just in time while I was fixing other things :)
Fortunately, this issue could be fixed with just a few lines and no new error variant in 441ea7b10e929d1de0c86e0bbb4eac8ac6bb9097
