### ISSUE TITLE
Crash on `Record::update_sequence_array_count`, substraction overflow

### ISSUE THREAD

**Issue by Arthur-PI** [ColinFinck/ntfs#26]
In `Record::update_sequence_array_count`, there is a case where `update_sequence` is 0 and is subtracted of `sizeof<u16>` which is 2 and so it overflows to below 0 for an `u16`.
https://github.com/ColinFinck/ntfs/blob/7dce76c77ca4e1f218e672adbb27b144cf0fb304/src/record.rs#L107-L113
A `saturating_sub` works here but not sure it is the preferred option 🤔

**Comment by ColinFinck** [comment]
Fixed in 5cc24169cf510295f53d9969d7bbd75f0b7711b9
