### ISSUE TITLE
Is it safe to scan a live disk?

### ISSUE THREAD

**Issue by santagada** [ColinFinck/ntfs#27]
I looked at the code but couldn't judge how safe is it to read directory entry tables directly with this on a live system? I mean, how safe is it to scan a whole disk lets say 5-10 tb while it is being heavily written, with potentially some deletes happening? Can you be reading a folder and it be deleted while reading contents or lets say a file in the folder is deleted?

I'm planning to write some code to do multi threaded full disk scans based on the directory entries only. I know it can be done as this software does it https://diskanalyzer.com/about but I'm weary that I don't remember seeing any write order guarantees on disk to say that what you are reading is consistent. Maybe reading each folder twice and if both matches its the correct entry?

**Comment by santagada** [comment]
Also If I get around to it would anyone be interested in the code?

**Comment by ColinFinck** [comment]
> I looked at the code but couldn't judge how safe is it to read directory entry tables directly with this on a live system? I mean, how safe is it to scan a whole disk lets say 5-10 tb while it is being heavily written, with potentially some deletes happening? Can you be reading a folder and it be deleted while reading contents or lets say a file in the folder is deleted?

My current `ntfs` crate is read-only and doesn't modify the filesystem at all. As a result, it cannot impact the consistency of your filesystem if you use it to read a filesystem that is also being modified right now.

As for crash safety, the crate may return an `NtfsError` whenever it hits an inconsistent filesystem state. For example, this may be the case when the operating system's filesystem driver concurrently writes to it or when a structure that you are operating on has just been deleted. However, the crate should never crash on invalid data. Special emphasis on this has been put in the recent releases.

Considering how NTFS works, you should be able to access some deleted files and folders using my crate (if you know their file record numbers or simply try out numbers). While the pointers to these files/folders may have been overwritten on disk, the underlying structures are often still intact.

Anyway, if you plan to scan filesystems in the terabyte range, please note that the current version of my crate has not been optimized for performance at all. Your scan may be very slow.

Hope this helps.
